import type { Property, Inquiry, User, CalendarEvent } from '../types';
import {
  saveProperties,
  saveInquiries,
  saveUsers,
  saveCalendarEvents,
  setInitialized,
} from './storage';

export function loadSampleData(): void {
  const properties: Property[] = [
    {
      id: 1,
      name: 'Sunset Villa',
      address: {
        street: '123 Sunset Boulevard',
        barangay: 'Poblacion',
        city: 'Makati',
        province: 'Metro Manila',
        zip: '1200',
      },
      price: 3500000,
      status: 'Available',
      type: 'House',
      photos: [
        'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
      ],
      description:
        'Beautiful 3-bedroom house with modern amenities in prime Makati location.',
      features: ['3 Bedrooms', '2 Bathrooms', 'Garage', 'Garden', '150 sqm'],
      reservationFee: 100000,
      commission: 70000,
      createdAt: '2025-11-01T10:00:00Z',
    },
    {
      id: 2,
      name: 'Ocean View Condo',
      address: {
        street: '456 Bayshore Avenue',
        barangay: 'Fort Bonifacio',
        city: 'Taguig',
        province: 'Metro Manila',
        zip: '1634',
      },
      price: 5200000,
      status: 'Available',
      type: 'Condo',
      photos: [
        'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
      ],
      description: 'Luxury 2-bedroom condo with stunning ocean views in BGC.',
      features: ['2 Bedrooms', '2 Bathrooms', 'Balcony', 'Pool Access', '95 sqm'],
      reservationFee: 150000,
      commission: 104000,
      createdAt: '2025-11-02T10:00:00Z',
    },
    {
      id: 3,
      name: 'Modern Townhouse',
      address: {
        street: '789 Commonwealth Avenue',
        barangay: 'Batasan Hills',
        city: 'Quezon City',
        province: 'Metro Manila',
        zip: '1126',
      },
      price: 4800000,
      status: 'Reserved',
      type: 'Townhouse',
      photos: [
        'https://images.unsplash.com/photo-1580587771525-78b9dba3b914',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
      ],
      description: 'Contemporary 3-bedroom townhouse in a gated community.',
      features: ['3 Bedrooms', '3 Bathrooms', '2 Parking', 'Rooftop', '120 sqm'],
      reservationFee: 120000,
      commission: 96000,
      createdAt: '2025-11-03T10:00:00Z',
    },
    {
      id: 4,
      name: 'City Center Apartment',
      address: {
        street: '321 Shaw Boulevard',
        barangay: 'Kapitolyo',
        city: 'Pasig',
        province: 'Metro Manila',
        zip: '1600',
      },
      price: 2800000,
      status: 'Available',
      type: 'Condo',
      photos: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
      ],
      description: 'Affordable 1-bedroom apartment perfect for young professionals.',
      features: ['1 Bedroom', '1 Bathroom', 'Parking', 'Gym Access', '45 sqm'],
      reservationFee: 80000,
      commission: 56000,
      createdAt: '2025-11-04T10:00:00Z',
    },
    {
      id: 5,
      name: 'Garden Estate',
      address: {
        street: '567 Roxas Boulevard',
        barangay: 'Malate',
        city: 'Manila',
        province: 'Metro Manila',
        zip: '1004',
      },
      price: 8500000,
      status: 'Pending',
      type: 'House',
      photos: [
        'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
      ],
      description: 'Elegant 5-bedroom house with expansive garden area.',
      features: ['5 Bedrooms', '4 Bathrooms', '3 Parking', 'Garden', '300 sqm'],
      reservationFee: 200000,
      commission: 170000,
      createdAt: '2025-11-05T10:00:00Z',
    },
    {
      id: 6,
      name: 'Prime Lot - Cavite',
      address: {
        street: 'Block 12 Lot 34',
        barangay: 'San Agustin',
        city: 'Dasmariñas',
        province: 'Cavite',
        zip: '4114',
      },
      price: 1200000,
      status: 'Available',
      type: 'Lot',
      photos: [
        'https://images.unsplash.com/photo-1500382017468-9049fed747ef',
        'https://images.unsplash.com/photo-1464146072230-91cabc968266',
      ],
      description: 'Residential lot in a prime location, ready for development.',
      features: ['250 sqm', 'Clean Title', 'Flood-free', 'Near Highway'],
      reservationFee: 50000,
      commission: 24000,
      createdAt: '2025-11-06T10:00:00Z',
    },
    {
      id: 7,
      name: 'Beach House - Batangas',
      address: {
        street: '888 Coastal Road',
        barangay: 'Wawa',
        city: 'Nasugbu',
        province: 'Batangas',
        zip: '4231',
      },
      price: 12000000,
      status: 'Available',
      type: 'House',
      photos: [
        'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2',
        'https://images.unsplash.com/photo-1502005097973-6a7082348e28',
      ],
      description: 'Stunning beach house with private beach access.',
      features: ['4 Bedrooms', '3 Bathrooms', 'Beach Access', 'Pool', '250 sqm'],
      reservationFee: 300000,
      commission: 240000,
      createdAt: '2025-11-07T10:00:00Z',
    },
    {
      id: 8,
      name: 'Cozy Studio Condo',
      address: {
        street: '234 Aurora Boulevard',
        barangay: 'Cubao',
        city: 'Quezon City',
        province: 'Metro Manila',
        zip: '1109',
      },
      price: 1800000,
      status: 'Available',
      type: 'Condo',
      photos: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
      ],
      description: 'Perfect starter home for singles or couples.',
      features: ['Studio', '1 Bathroom', 'Parking', 'Near MRT', '28 sqm'],
      reservationFee: 60000,
      commission: 36000,
      createdAt: '2025-11-08T10:00:00Z',
    },
    {
      id: 9,
      name: 'Commercial Lot - QC',
      address: {
        street: '999 EDSA',
        barangay: 'Kamuning',
        city: 'Quezon City',
        province: 'Metro Manila',
        zip: '1103',
      },
      price: 25000000,
      status: 'Available',
      type: 'Commercial',
      photos: [
        'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab',
        'https://images.unsplash.com/photo-1449844908441-8829872d2607',
      ],
      description: 'Prime commercial lot along EDSA, perfect for business.',
      features: ['500 sqm', 'Corner Lot', 'High Traffic', 'Commercial Zone'],
      reservationFee: 500000,
      commission: 500000,
      createdAt: '2025-11-09T10:00:00Z',
    },
    {
      id: 10,
      name: 'Family Townhouse',
      address: {
        street: '111 East Avenue',
        barangay: 'Barangka',
        city: 'Mandaluyong',
        province: 'Metro Manila',
        zip: '1550',
      },
      price: 6200000,
      status: 'Available',
      type: 'Townhouse',
      photos: [
        'https://images.unsplash.com/photo-1600585154526-990dced4db0d',
        'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde',
      ],
      description: 'Spacious family home with modern amenities.',
      features: ['4 Bedrooms', '3 Bathrooms', '2 Parking', 'Garden', '180 sqm'],
      reservationFee: 150000,
      commission: 124000,
      createdAt: '2025-11-10T10:00:00Z',
    },
  ];

  const users: User[] = [
    {
      id: 1,
      name: 'Admin User',
      email: 'admin@tesproperty.com',
      password: 'admin123',
      role: 'admin',
      phone: '0917-000-0000',
      active: true,
      activeInquiries: 0,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 2,
      name: 'Maria Santos',
      email: 'maria@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-111-1111',
      active: true,
      activeInquiries: 8,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 3,
      name: 'Pedro Garcia',
      email: 'pedro@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-222-2222',
      active: true,
      activeInquiries: 5,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 4,
      name: 'Juan dela Cruz',
      email: 'juan@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-333-3333',
      active: true,
      activeInquiries: 3,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 5,
      name: 'Anna Reyes',
      email: 'anna@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-444-4444',
      active: true,
      activeInquiries: 6,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 6,
      name: 'Carlos Lopez',
      email: 'carlos@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-555-5555',
      active: true,
      activeInquiries: 4,
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 7,
      name: 'Sofia Mendoza',
      email: 'sofia@tesproperty.com',
      password: 'agent123',
      role: 'agent',
      phone: '0917-666-6666',
      active: true,
      activeInquiries: 7,
      createdAt: '2025-01-01T00:00:00Z',
    },
  ];

  const inquiries: Inquiry[] = [
    {
      id: 1,
      propertyId: 1,
      propertyName: 'Sunset Villa',
      customerName: 'John Doe',
      customerEmail: 'john.doe@email.com',
      customerPhone: '0917-777-7777',
      customerAddress: 'Makati City',
      message: 'Interested in viewing this property next week.',
      status: 'Assigned',
      assignedAgentId: 2,
      assignedAgentName: 'Maria Santos',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-01T10:00:00Z',
      updatedAt: '2025-12-01T11:00:00Z',
    },
    {
      id: 2,
      propertyId: 2,
      propertyName: 'Ocean View Condo',
      customerName: 'Jane Smith',
      customerEmail: 'jane.smith@email.com',
      customerPhone: '0917-888-8888',
      customerAddress: 'Taguig City',
      message: 'Looking for a condo with ocean view.',
      status: 'Viewing Scheduled',
      assignedAgentId: 2,
      assignedAgentName: 'Maria Santos',
      viewingDate: '2025-12-15T14:00:00Z',
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Customer prefers afternoon viewing',
      createdAt: '2025-12-02T10:00:00Z',
      updatedAt: '2025-12-02T11:00:00Z',
    },
    {
      id: 3,
      propertyId: 3,
      propertyName: 'Modern Townhouse',
      customerName: 'Robert Johnson',
      customerEmail: 'robert.j@email.com',
      customerPhone: '0917-999-9999',
      customerAddress: 'Quezon City',
      message: 'Ready to make a deposit if suitable.',
      status: 'Deposit Paid',
      assignedAgentId: 3,
      assignedAgentName: 'Pedro Garcia',
      viewingDate: '2025-12-10T10:00:00Z',
      depositAmount: 120000,
      reservationExpiryDate: '2025-12-24T10:00:00Z',
      notes: 'Deposit paid on Dec 10, 2025',
      createdAt: '2025-12-03T10:00:00Z',
      updatedAt: '2025-12-10T10:30:00Z',
    },
    {
      id: 4,
      propertyId: 4,
      propertyName: 'City Center Apartment',
      customerName: 'Emily Davis',
      customerEmail: 'emily.d@email.com',
      customerPhone: '0918-111-1111',
      customerAddress: 'Pasig City',
      message: 'First time buyer, need guidance.',
      status: 'In Progress',
      assignedAgentId: 4,
      assignedAgentName: 'Juan dela Cruz',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Needs financing assistance',
      createdAt: '2025-12-04T10:00:00Z',
      updatedAt: '2025-12-04T11:00:00Z',
    },
    {
      id: 5,
      propertyId: 5,
      propertyName: 'Garden Estate',
      customerName: 'Michael Brown',
      customerEmail: 'michael.b@email.com',
      customerPhone: '0918-222-2222',
      customerAddress: 'Manila',
      message: 'Interested in this property for my family.',
      status: 'Viewed - Interested',
      assignedAgentId: 5,
      assignedAgentName: 'Anna Reyes',
      viewingDate: '2025-12-08T15:00:00Z',
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Very interested, preparing documents',
      createdAt: '2025-12-05T10:00:00Z',
      updatedAt: '2025-12-08T16:00:00Z',
    },
    {
      id: 6,
      propertyId: 1,
      propertyName: 'Sunset Villa',
      customerName: 'Sarah Wilson',
      customerEmail: 'sarah.w@email.com',
      customerPhone: '0918-333-3333',
      customerAddress: 'Makati City',
      message: 'Can we schedule a viewing this Saturday?',
      status: 'New',
      assignedAgentId: null,
      assignedAgentName: null,
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-07T10:00:00Z',
      updatedAt: '2025-12-07T10:00:00Z',
    },
    {
      id: 7,
      propertyId: 6,
      propertyName: 'Prime Lot - Cavite',
      customerName: 'David Martinez',
      customerEmail: 'david.m@email.com',
      customerPhone: '0918-444-4444',
      customerAddress: 'Cavite',
      message: 'Planning to build a house, need vacant lot.',
      status: 'Assigned',
      assignedAgentId: 6,
      assignedAgentName: 'Carlos Lopez',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-06T10:00:00Z',
      updatedAt: '2025-12-06T11:00:00Z',
    },
    {
      id: 8,
      propertyId: 7,
      propertyName: 'Beach House - Batangas',
      customerName: 'Lisa Anderson',
      customerEmail: 'lisa.a@email.com',
      customerPhone: '0918-555-5555',
      customerAddress: 'Makati City',
      message: 'Looking for a vacation home.',
      status: 'Viewing Scheduled',
      assignedAgentId: 7,
      assignedAgentName: 'Sofia Mendoza',
      viewingDate: '2025-12-20T09:00:00Z',
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Weekend viewing scheduled',
      createdAt: '2025-12-05T10:00:00Z',
      updatedAt: '2025-12-05T11:00:00Z',
    },
    {
      id: 9,
      propertyId: 8,
      propertyName: 'Cozy Studio Condo',
      customerName: 'James Taylor',
      customerEmail: 'james.t@email.com',
      customerPhone: '0918-666-6666',
      customerAddress: 'Quezon City',
      message: 'Need a studio near my workplace.',
      status: 'In Progress',
      assignedAgentId: 2,
      assignedAgentName: 'Maria Santos',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-04T10:00:00Z',
      updatedAt: '2025-12-04T11:00:00Z',
    },
    {
      id: 10,
      propertyId: 2,
      propertyName: 'Ocean View Condo',
      customerName: 'Patricia White',
      customerEmail: 'patricia.w@email.com',
      customerPhone: '0918-777-7777',
      customerAddress: 'Taguig City',
      message: 'Can you provide more photos?',
      status: 'Viewed - Undecided',
      assignedAgentId: 3,
      assignedAgentName: 'Pedro Garcia',
      viewingDate: '2025-12-09T11:00:00Z',
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Needs time to decide',
      createdAt: '2025-12-03T10:00:00Z',
      updatedAt: '2025-12-09T12:00:00Z',
    },
    {
      id: 11,
      propertyId: 9,
      propertyName: 'Commercial Lot - QC',
      customerName: 'Christopher Harris',
      customerEmail: 'chris.h@email.com',
      customerPhone: '0918-888-8888',
      customerAddress: 'Quezon City',
      message: 'Interested for business purposes.',
      status: 'Assigned',
      assignedAgentId: 4,
      assignedAgentName: 'Juan dela Cruz',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-06T10:00:00Z',
      updatedAt: '2025-12-06T11:00:00Z',
    },
    {
      id: 12,
      propertyId: 10,
      propertyName: 'Family Townhouse',
      customerName: 'Nancy Clark',
      customerEmail: 'nancy.c@email.com',
      customerPhone: '0918-999-9999',
      customerAddress: 'Mandaluyong City',
      message: 'Looking for a family home with garden.',
      status: 'New',
      assignedAgentId: null,
      assignedAgentName: null,
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: '',
      createdAt: '2025-12-08T10:00:00Z',
      updatedAt: '2025-12-08T10:00:00Z',
    },
    {
      id: 13,
      propertyId: 1,
      propertyName: 'Sunset Villa',
      customerName: 'Daniel Lewis',
      customerEmail: 'daniel.l@email.com',
      customerPhone: '0919-111-1111',
      customerAddress: 'Makati City',
      message: 'Interested in this property.',
      status: 'Viewed - Not Interested',
      assignedAgentId: 5,
      assignedAgentName: 'Anna Reyes',
      viewingDate: '2025-12-07T10:00:00Z',
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Not suitable, too far from work',
      createdAt: '2025-12-05T10:00:00Z',
      updatedAt: '2025-12-07T11:00:00Z',
    },
    {
      id: 14,
      propertyId: 4,
      propertyName: 'City Center Apartment',
      customerName: 'Karen Walker',
      customerEmail: 'karen.w@email.com',
      customerPhone: '0919-222-2222',
      customerAddress: 'Pasig City',
      message: 'Is financing available?',
      status: 'Cancelled',
      assignedAgentId: 6,
      assignedAgentName: 'Carlos Lopez',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Customer found another property',
      createdAt: '2025-12-02T10:00:00Z',
      updatedAt: '2025-12-05T10:00:00Z',
    },
    {
      id: 15,
      propertyId: 6,
      propertyName: 'Prime Lot - Cavite',
      customerName: 'Steven Hall',
      customerEmail: 'steven.h@email.com',
      customerPhone: '0919-333-3333',
      customerAddress: 'Cavite',
      message: 'Ready to purchase if the lot is suitable.',
      status: 'In Progress',
      assignedAgentId: 7,
      assignedAgentName: 'Sofia Mendoza',
      viewingDate: null,
      depositAmount: null,
      reservationExpiryDate: null,
      notes: 'Scheduled site visit next week',
      createdAt: '2025-12-07T10:00:00Z',
      updatedAt: '2025-12-07T11:00:00Z',
    },
  ];

  const calendarEvents: CalendarEvent[] = [
    {
      id: 1,
      title: 'Property Viewing - Ocean View Condo',
      type: 'viewing',
      status: 'confirmed',
      propertyId: 2,
      propertyName: 'Ocean View Condo',
      inquiryId: 2,
      agentId: 2,
      agentName: 'Maria Santos',
      customerName: 'Jane Smith',
      date: '2025-12-15',
      startTime: '14:00',
      endTime: '15:00',
      notes: 'Customer prefers afternoon viewing',
      createdAt: '2025-12-02T11:00:00Z',
    },
    {
      id: 2,
      title: 'Property Viewing - Beach House',
      type: 'viewing',
      status: 'confirmed',
      propertyId: 7,
      propertyName: 'Beach House - Batangas',
      inquiryId: 8,
      agentId: 7,
      agentName: 'Sofia Mendoza',
      customerName: 'Lisa Anderson',
      date: '2025-12-20',
      startTime: '09:00',
      endTime: '11:00',
      notes: 'Weekend viewing, bring complete property documents',
      createdAt: '2025-12-05T11:00:00Z',
    },
    {
      id: 3,
      title: 'Personal Day Off',
      type: 'unavailable',
      status: 'unavailable',
      propertyId: null,
      propertyName: null,
      inquiryId: null,
      agentId: 4,
      agentName: 'Juan dela Cruz',
      customerName: null,
      date: '2025-12-18',
      startTime: '09:00',
      endTime: '17:00',
      notes: 'Day off for personal matters',
      createdAt: '2025-12-01T10:00:00Z',
    },
  ];

  // Save all data to localStorage
  saveProperties(properties);
  saveUsers(users);
  saveInquiries(inquiries);
  saveCalendarEvents(calendarEvents);
  setInitialized(true);
}
